// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ChinookLibrary.Data;
using ChinookLibrary.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace ChinookLibrary.Data.Configurations
{
    public partial class PlaylistTrackConfiguration : IEntityTypeConfiguration<PlaylistTrack>
    {
        public void Configure(EntityTypeBuilder<PlaylistTrack> entity)
        {
            entity.HasKey(e => new { e.PlaylistId, e.TrackId })
                .IsClustered(false);

            entity.HasIndex(e => e.TrackId, "IFK_PlaylistTrackTrackId");

            entity.HasOne(d => d.Playlist)
                .WithMany(p => p.PlaylistTrack)
                .HasForeignKey(d => d.PlaylistId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PlaylistTrackPlaylistId");

            entity.HasOne(d => d.Track)
                .WithMany(p => p.PlaylistTrack)
                .HasForeignKey(d => d.TrackId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PlaylistTrackTrackId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PlaylistTrack> entity);
    }
}
